server:
  port: 8001

#mybatis的整合
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.ns.sso.entities
  mapper-locations: classpath:mybatis/mapper/*.xml
#  configuration:
#    map-underscore-to-camel-case: true


#spring的整合
spring:
  application:
    name: xns-service-sso
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sso
    username: root
    password: tian787604
    druid:
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall
      use-global-data-source-stat: true

#  thymeleaf:
#    cache: false #关闭缓存，不然无法看到实时页面
#    mode: LEGACYHTML5
#    encoding: UTF-8
#    servlet:
#      content-type: text/html

  mvc:
    static-path-pattern: /**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: service-sso8001
    prefer-ip-address: true

feign:
  hystrix:
    enabled: true

info:
  app.name: xns-sso
  company.name: www.xns.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
