server:
  port: 8301

spring:
  application:
    name: servicecloud-redis
  redis:
    #密码
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    password: tian787604
    port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: servicecloud-redis8301
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app.name: xns-sso
  company.name: www.xns.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$