server:
  port: 8301

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: service-redis8301
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app.name: xns-sso
  company.name: www.xns.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

spring:
  redis:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0