server:
  port: 8301

spring:
  application:
    name: servicecloud-redis
  redis:
    #密码
    lettuce:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 1500
        #连接池中的最大空闲连接
        max-idle: 500
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最小空闲连接
        min-idle: 100
    host: 127.0.0.1
    port: 6379
    password: tian2189543

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: servicecloud-redis8301
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app.name: xns-sso
  company.name: www.xns.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$