server:
  port: 8002

#mybatis的整合
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.ns.sso.entities
  mapper-locations: classpath:mybatis/mapper/*.xml
#  configuration:
#    map-underscore-to-camel-case: true

spring:
  application:
    name: xns-service-lottery
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xns_lottery
    username: root
    password: tian787604
    druid:
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall
      use-global-data-source-stat: true

  rabbitmq:
    #不能为localhost,否则报错
    host: 127.0.0.1
    #15672是Web管理界面的端口；5672是访问的端口
    port: 5672
    username: xns
    password: xns2189543
    #这个虚拟的东西一定要授权
    virtual-host: /xns_lottery
    #开启消息确认机制
    publisher-confirms: true


eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: service-lottery8002
    prefer-ip-address: true

feign:
  hystrix:
    enabled: true

info:
  app.name: xns-sso
  company.name: www.xns.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

  mvc:
    static-path-pattern: /**