server:
  port: 8003

spring:
  application:
    name: xns-service-sample2

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: service-sample8003
    prefer-ip-address: true

feign:
  hystrix:
    enabled: true

info:
  app.name: xns-sso
  company.name: www.xns.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

  mvc:
    static-path-pattern: /**